/* Generated by SharpKit 5 v5.4.4 */

if (typeof(JsTypes) == "undefined")
    var JsTypes = [];
var Rotate = {
    fullname: "Rotate",
    baseTypeName: "UnityEngine.MonoBehaviour",
    assemblyName: "SharpKitWebApp1",
    Kind: "Class",
    definition: {
        ctor: function (){
            this.speed = 0.1;
            this.mTrans = null;
            this.rotateVar = new UnityEngine.Vector3.ctor();
            //UnityEngine.MonoBehaviour.ctor.call(this);
        },
        Start: function (){
        },
        Update: function (){
            if (UnityEngine.Object.op_Equality(this.mTrans, null)){
                this.mTrans = this.get_transform();
                this.rotateVar = new UnityEngine.Vector3.ctor$$Single$$Single$$Single(0.5, 0.5, 0);
            }
            this.mTrans.Rotate$$Vector3(this.rotateVar);
        }
    }
};
JsTypes.push(Rotate);

