// 1) Files generated by JSBinding
//--------------------------------------------------
   // will be automatically included in C# code

// 2) Manually written js
// will overwrite some functions in step 1)
//--------------------------------------------------
CS.require("Manual/UnityEngine_Vector3");
//
// may be more..
//

// 3) SharpKit library
//--------------------------------------------------
CS.require("SharpKit/jsclr");
CS.require("SharpKit/clrlibrary");

// 4) code generated by SharpKit
//--------------------------------------------------
CS.require("SharpKitGeneratedFiles");

// 5) SharpKit handler (Compile)
//--------------------------------------------------
CS.require("SharpKit/myclrhandler");

// 6) Error handler
//--------------------------------------------------
CS.require("ErrorHandler");

