/*
* Author: Qiucw
* DO NOT change order
*/

// 0) SharpKit library
//--------------------------------------------------
CS.require("SharpKit/jsclr");
CS.require("SharpKit/clrlibrary");

// 1) Files generated by JSBinding
// may overwrite some classes in step 0)
//--------------------------------------------------
CS.require("GeneratedFiles");




// 2) Manually written js
// will overwrite some functions in step 1)
//--------------------------------------------------
CS.require("Manual/UnityEngine_Vector3");
CS.require("Manual/UnityEngine_Vector2");
//
// may be more..
//

// 3) code generated by SharpKit
//--------------------------------------------------
CS.require("SharpKitGeneratedFiles");

// 4) SharpKit handler (Compile)
//--------------------------------------------------
CS.require("SharpKit/myclrhandler");

// 5) Error handler
//--------------------------------------------------
CS.require("ErrorHandler");

