/* Generated by JSBinding.
* see JSAnalyzer.cs / OutputAllTypesWithJsTypeAttribute() function
* better not modify manually.
*/

CS.require("SharpKitGenerated/JSBinding/Samples/Serialization/SerializeSimple.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Serialization/SerializeStruct.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Serialization/AppleInfo.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/V3Test.javascript");
