/* Generated by JSBinding.
* see JSAnalyzer.cs / OutputAllTypesWithJsTypeAttribute() function
* better not modify manually.
*/

CS.require("SharpKitGenerated/JSBinding/JSImp/Coroutine.javascript");
CS.require("SharpKitGenerated/JSBinding/JSImp/Iterator.javascript");
CS.require("SharpKitGenerated/JSBinding/JSImp/Reflection.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/ComponentTest/ComponentTest.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/ComponentTest/TEnemy.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/ComponentTest/TEnemyBase.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Coroutine/TestCoroutine.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/DelegateTest.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/DictionaryTest.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/EncodingTest.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/JSImpTest/JSImpTest1.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/JSImpTest/Person.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/JSImpTest/XmlParser.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/ListTest.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/PerformanceTest1.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/SampleViewer.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/stScene.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Serialization/Car.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Serialization/SerializeSimple.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Serialization/SerializeStruct.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Serialization/AppleInfo.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Serialization/Wheel.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/V3Test.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/XmlTest.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/ShopItemData.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/LimitDayNum.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/LimitVIPLevel.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/LimitBuyNumPrices.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/LimitVipDayNum.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/LimeTimeNum.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/IShopLime.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/ItemType.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/ItemCell.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/ColorSign.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/enumMoneyType.javascript");
CS.require("SharpKitGenerated/JSBinding/Samples/Xml/XmlUtils.javascript");
